### ISSUE TITLE
Website lists wrong license

### ISSUE THREAD

**Issue by heinrich5991** [flathub/tw.ddnet.ddnet#32]
https://flathub.org/apps/details/tw.ddnet.ddnet shows the license to be "CC-BY-SA-3.0 and Apache-2.0" but the DDNet project isn't under the Apache-2.0 license. I think it's the zlib license.

**Comment by ElXreno** [comment]
If I understand correctly, the license is taken from the [AppStream XML file](https://github.com/ddnet/ddnet/blob/c479230d714725754c93e516e3cde7fb96aac0c8/other/ddnet.appdata.xml#L5).

**Comment by miguilimzero** [comment]
@ElXreno can you help me with this? It seems you added the Apache-2.0 license to the .XML file (https://github.com/ddnet/ddnet/pull/2021).

**Comment by heinrich5991** [comment]
The license file is here: https://github.com/ddnet/ddnet/blob/efe593c7b06bdbe2ff0532b6cb278b093298973f/license.txt.

Compare https://choosealicense.com/licenses/zlib/.

**Comment by miguilimzero** [comment]
@heinrich5991 So the correct thing would be to remove Apache-2.0 and leave only CC-BY-SA-3.0?

**Comment by heinrich5991** [comment]
No. It's zlib for the code and CC-BY-SA-3.0 for the data files.
