### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by ElXreno** [flathub/tw.ddnet.ddnet#39]
Unfortunately, at the moment I do not have enough time to support this package, and very soon I will have to give up everything for a long time.

Is someone willing to take over maintaining `tw.ddnet.ddnet`?

**Comment by ElXreno** [comment]
I apologize for the long delay.
I will ask the Flathub team to give you the necessary permissions.

**Comment by rffontenelle** [comment]
Can be closed, I assume
