### ISSUE TITLE
Rename app-id to org.ddnet.ddnet ?

### ISSUE THREAD

**Issue by rffontenelle** [flathub/tw.ddnet.ddnet#50]
Considering that the upstream changed its website from ddnet.tw to ddnet.org, how about making it `org.ddnet.ddnet`? Looks like the process is the file a pull request with the new one and then [mark this as EOL](https://docs.flathub.org/docs/for-app-authors/maintenance/#end-of-life)

**Comment by miguilimzero** [comment]
Sure! I'll be doing that soon.

**Comment by heinrich5991** [comment]
The application hasn't been renamed, there's theoretically no reason to prompt the user (which this change will do, according to the documentation). The ddnet.tw domain is still under our control and redirects to ddnet.org.

**Comment by miguilimzero** [comment]
@heinrich5991 The app renaming would be to comply with the new domain TLD. The old .tw is still owned by ddnet and redirects to the new one, but it's still not the final domain. 

The documentation says: "The end-of-life-rebase will tell flatpak to automatically migrate the user data from the old package to the new package, making the process transparent for the user.". So it should be a smooth transition.

I don't see a reason not to make this change. It doesn't seem to break anything.

**Comment by heinrich5991** [comment]
> The documentation says: "The end-of-life-rebase will tell flatpak to automatically migrate the user data from the old package to the new package, making the process transparent for the user.".

I see. If this requires no action from the user whatsoever, then it's not bad.

It also comes with no advantages as it would seem (only updating from one domain to another, both owned by DDNet for the forseeable future), so if the users had to do anything manually, it wouldn't be worth it in my view.

**Comment by heinrich5991** [comment]
Wait, the documentation says the user will have to get involved:
> If the application has been renamed, you can additionally include end-of-life-rebase with the new ID. Recent flatpak versions will prompt user if they'd like to switch to the renamed app.

Then I'd suggest not doing it, it doesn't seem to have any practical advantage.

**Comment by rffontenelle** [comment]
Oh well. When I filed this issue I was expecting to be a simple and harmless change. Now it looks more controversial and problematic to the user. Probably it's better to keep as is.
